MealManagementSoftwareUI/Controllers/OrderItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MealManagementSoftwareDataLayer;
using MealManagementSoftwareDataLayer;

namespace MealManagementSoftwareUiLayer.Controllers
{
    public class OrderItemsController : Controller
    {
        private readonly MealManagementDbContext _context;

        public OrderItemsController(MealManagementDbContext context)
        {
            _context = context;
        }

        // GET: OrderItems
        [Route("/OrderItems/Index/{orderId}")]
        public async Task<IActionResult> Index(long? orderId)
        {
            var canteenSystemDbContext = orderId == null?
                  _context.OrderItems
                .Include(o => o.MealMenu).Include(o => o.Order):
                _context.OrderItems.Where(x=>x.OrderId == orderId)
                .Include(o => o.MealMenu).Include(o => o.Order);
            return View(await canteenSystemDbContext.ToListAsync());
        }

        // GET: OrderItems/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderItem = await _context.OrderItems
                .Include(o => o.MealMenu)
                .Include(o => o.Order)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orderItem == null)
            {
                return NotFound();
            }

            return View(orderItem);
        }

        // GET: OrderItems/Create
        public IActionResult Create()
        {
            ViewData["MealMenuId"] = new SelectList(_context.MealMenus, "Id", "MealName");
            ViewData["OrderId"] = new SelectList(_context.Orders, "Id", "OrderReference");
            return View();
        }

        // POST: OrderItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MealMenuId,MealMenuOrderDate,OrderId,Quantity,Price")] DishOrderItem orderItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orderItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MealMenuId"] = new SelectList(_context.MealMenus, "Id", "MealName", orderItem.MealMenuId);
            ViewData["OrderId"] = new SelectList(_context.Orders, "Id", "OrderReference", orderItem.OrderId);
            return View(orderItem);
        }

        // GET: OrderItems/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderItem = await _context.OrderItems.FindAsync(id);
            if (orderItem == null)
            {
                return NotFound();
            }
            ViewData["MealMenuId"] = new SelectList(_context.MealMenus, "Id", "MealName", orderItem.MealMenuId);
            ViewData["OrderId"] = new SelectList(_context.Orders, "Id", "OrderReference", orderItem.OrderId);
            return View(orderItem);
        }

        // POST: OrderItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,MealMenuId,MealMenuOrderDate,OrderId,Quantity,Price")] DishOrderItem orderItem)
        {
            if (id != orderItem.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orderItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderItemExists(orderItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MealMenuId"] = new SelectList(_context.MealMenus, "Id", "MealName", orderItem.MealMenuId);
            ViewData["OrderId"] = new SelectList(_context.Orders, "Id", "OrderReference", orderItem.OrderId);
            return View(orderItem);
        }

        // GET: OrderItems/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderItem = await _context.OrderItems
                .Include(o => o.MealMenu)
                .Include(o => o.Order)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orderItem == null)
            {
                return NotFound();
            }

            return View(orderItem);
        }

        // POST: OrderItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var orderItem = await _context.OrderItems.FindAsync(id);
            _context.OrderItems.Remove(orderItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderItemExists(long id)
        {
            return _context.OrderItems.Any(e => e.Id == id);
        }
    }
}

MealManagementSoftwareUI/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore; 
using MealManagementSoftwareUiLayer.ViewModel;
using System.Net.Mail;
using System.Net;
using MealManagementSoftwareDataLayer;
using MealManagementSoftwareDataLayer;

namespace MealManagementSoftwareUiLayer.Controllers
{
    public class OrdersController : Controller
    {
        private readonly MealManagementDbContext _context;

        public OrdersController(MealManagementDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> OrderConfirmation(string notificationMessage)
        { 
            return View(new ProductOrderConfirmViewModel(notificationMessage));
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var canteenSystemDbContext = _context.Orders.Include(o => o.UserProfile)
                .Include(o => o.Payments);
            return View(await canteenSystemDbContext.ToListAsync());
        }

       [Route("orders/studentorder/{userId}")]
        public async Task<IActionResult> StudentOrder(int userId)
        {
            var canteenSystemDbContext = _context.Orders.Where(x => x.UserProfileId == userId)
                .Include(o => o.UserProfile).Include(o => o.Payments);
               
            var orders = await canteenSystemDbContext.ToListAsync();
            return View(orders);
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.UserProfile)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["UserProfileId"] = new SelectList(_context.UserProfiles, "Id", "Department");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,OrderReference,UserProfileId,TotalPrice,CreatedDate,UpdatedDate")] DishOrder order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserProfileId"] = new SelectList(_context.UserProfiles, "Id", "Department", order.UserProfileId);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["UserProfileId"] = new SelectList(_context.UserProfiles, "Id", "Department", order.UserProfileId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,OrderReference,UserProfileId,TotalPrice,CreatedDate,UpdatedDate")] DishOrder order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserProfileId"] = new SelectList(_context.UserProfiles, "Id", "Department", order.UserProfileId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.UserProfile)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var order = await _context.Orders.FindAsync(id);
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(long id)
        {
            return _context.Orders.Any(e => e.Id == id);
        }

    }
}

MealManagementSoftwareUI/Views/Orders/Create.cshtml
@model MealManagementSoftwareDataLayer.DishOrder

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OrderReference" class="control-label"></label>
                <input asp-for="OrderReference" class="form-control" />
                <span asp-validation-for="OrderReference" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserProfileId" class="control-label"></label>
                <select asp-for="UserProfileId" class ="form-control" asp-items="ViewBag.UserProfileId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedDate" class="control-label"></label>
                <input asp-for="UpdatedDate" class="form-control" />
                <span asp-validation-for="UpdatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MealManagementSoftwareUI/Views/Orders/Delete.cshtml
@model MealManagementSoftwareDataLayer.DishOrder

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderReference)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderReference)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserProfile)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserProfile.Department)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MealManagementSoftwareUI/Views/Orders/Details.cshtml
@model MealManagementSoftwareDataLayer.DishOrder

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderReference)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderReference)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserProfile)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserProfile.Department)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MealManagementSoftwareUI/Views/Orders/Edit.cshtml
@model MealManagementSoftwareDataLayer.DishOrder

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="OrderReference" class="control-label"></label>
                <input asp-for="OrderReference" class="form-control" />
                <span asp-validation-for="OrderReference" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserProfileId" class="control-label"></label>
                <select asp-for="UserProfileId" class="form-control" asp-items="ViewBag.UserProfileId"></select>
                <span asp-validation-for="UserProfileId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedDate" class="control-label"></label>
                <input asp-for="UpdatedDate" class="form-control" />
                <span asp-validation-for="UpdatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MealManagementSoftwareUI/Views/Orders/Index.cshtml
@model IEnumerable<MealManagementSoftwareDataLayer.DishOrder>

@{
    ViewData["Title"] = "Orders";
}

<h1>Available orders</h1>
<div id="style-7" class="scrollbar">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.OrderReference)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedDate)
                </th>
                <th>
                    Student Name
                </th>
                <th>
                    Student Rollnumber
                </th>
                <th>
                    Is Paid
                </th>
                <th>
                    View detail
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderReference)
                    </td>
                    <td>
                        £ @Html.DisplayFor(modelItem => item.TotalPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedDate.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserProfile.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserProfile.RollNumber)
                    </td>
                    <td>
                        @(item.Payments != null && item.Payments.Any() ?"Yes":"No")
                    </td>
                    <td>
                        <a href="/OrderItems/Index/@item.Id">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    </div>
    <div class="text-center">
        <a class="btn btn-default" href="/home">Go to Home</a>
    </div>

MealManagementSoftwareUI/Views/Orders/OrderConfirmation.cshtml
@model  MealManagementSoftwareUiLayer.ViewModel.ProductOrderConfirmViewModel

@{
    ViewData["Title"] = "Order Confirmation";
}
<div class="text-center">


    <div class="alert alert-success" role="alert">
        @Model.NotificationMessage
    </div>


    <a class="btn btn-info" href="/home">Go to home</a>
</div>

MealManagementSoftwareUI/Views/Orders/StudentOrder.cshtml
@model IEnumerable<MealManagementSoftwareDataLayer.DishOrder>

@{
    ViewData["Title"] = "Orders";
}

<h1>Your orders</h1>
<div id="style-7" class="scrollbar">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.OrderReference)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedDate)
                </th>
                <th>
                    Is Paid
                </th>
                <th>
                    View detail
                </th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderReference)
                    </td>
                    <td>
                        £ @Html.DisplayFor(modelItem => item.TotalPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedDate.Date)
                    </td>
                    <td>
                        @(item.Payments != null && item.Payments.Any() ?"Yes":"No")
                    </td>
                    <td>
                        <a asp-action="Index" asp-controller="OrderItems" asp-route-id="@item.Id">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>
<div class="text-center">
    <a id="CancelBtn" class="btn btn-default" href="/home">Back to Home</a>
</div>